# config/meta.yml

meta_product_name: "hear4me"
meta_title: "hear4me - Transcreva seus áudios"
meta_description: "Recebeu muitos áudios hoje? Relaxa, a gente te resume e ainda te conta como a pessoa está se sentindo!"
meta_image: "listening-to-music.jpg" # image must exist in `app/assets/images/`
